### ISSUE TITLE
Crashes 

### ISSUE THREAD

**Issue by Rukia1727** [Zkaface/TAIGA#51]
This is the crash report and I'm not downgrading to a lower version of tinkers construct just to use this mod, it seems to be a problem with the version compatibility. 
---- Minecraft Crash Report ----

WARNING: coremods are present:
  MalisisCorePlugin (malisiscore-1.10.2-4.2.5.jar)
  NWRTweak (redstonepaste-mc1.9.4-1.7.4.jar)
  FMLPlugin (InventoryTweaks-1.61-58.jar)
  LoadingPluginBuildingBricks (BuildingBricks-1.10.2-2.0.12.jar)
Contact their authors BEFORE contacting forge

// Ooh. Shiny.

Time: 10/15/16 12:55 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderException: java.lang.NoSuchFieldError: enderference
	at net.minecraftforge.fml.common.LoadController.transition(LoadController.java:186)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:612)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:257)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:439)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:351)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NoSuchFieldError: enderference
	at com.sosnitzka.taiga.MaterialTraits.<clinit>(MaterialTraits.java:55)
	at com.sosnitzka.taiga.TAIGA.registerTinkerMaterials(TAIGA.java:140)
	at com.sosnitzka.taiga.TAIGA.preInit(TAIGA.java:57)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:597)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:239)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:217)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:142)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:609)
	... 10 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 305636232 bytes (291 MB) / 1189609472 bytes (1134 MB) up to 2386558976 bytes (2276 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2560m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.32 Powered by Forge 12.18.2.2099 31 mods loaded, 31 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCH	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCH	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.2.2099.jar) 
	UCH	Forge{12.18.2.2099} [Minecraft Forge] (forge-1.10.2-12.18.2.2099.jar) 
	UCH	buildingbrickshooks{1.10.2-2.0.12} [Building Bricks Hooks] (minecraft.jar) 
	UCH	mantle{1.10.2-1.0.0.jenkins170} [Mantle] (Mantle-1.10.2-1.0.0.jar) 
	UCH	tconstruct{1.10.2-2.5.5.jenkins393} [Tinkers' Construct] (TConstruct-1.10.2-2.5.5.jar) 
	UCH	thedragonlib{1.10.2-1.0.3.0} [TheDragonLib] (thedragonlib-1.10.2-1.0.3.0.jar) 
	UCH	armorplus{1.10.2-7.0.1.1.6} [ArmorPlus] (armorplus-1.10.2-7.0.1.1.6.jar) 
	UCH	basemetals{2.4.0} [Base Metals] (BaseMetals_1.10.2-2.4.0.11.jar) 
	UCE	buildingbricks{1.10.2-2.0.12} [Building Bricks] (BuildingBricks-1.10.2-2.0.12.jar) 
	UCH	JEI{3.12.7.321} [Just Enough Items] (jei_1.10.2-3.12.7.321.jar) 
	UCH	forestry{5.2.14.270} [Forestry] (forestry_1.10.2-5.2.14.270.jar) 
	UCH	hopperducts{1.4.8} [Hopper Ducts] (hopperducts-mc1.9.4-1.4.8.jar) 
	UCH	improvedHoes{1.1} [ImprovedHoes] (ImprovedHoes-1.10.2-1.1.jar) 
	UCH	inventorytweaks{1.61-58-a1fd884} [Inventory Tweaks] (InventoryTweaks-1.61-58.jar) 
	UCH	ironchest{1.10.2-7.0.11.797} [Iron Chest] (ironchest-1.10.2-7.0.11.797.jar) 
	UCH	journeymap{1.10.2-5.3.0b1} [JourneyMap] (journeymap-1.10.2-5.3.0b1-unlimited.jar) 
	UCH	jeresources{0.5.2.57} [Just Enough Resources] (JustEnoughResources-1.10.2-0.5.2.57.jar) 
	UCH	lootbags{2.1.3} [Loot Bags] (LootBags-1.10.2-2.1.3.jar) 
	UCH	malisiscore{1.10.2-4.2.5} [MalisisCore] (malisiscore-1.10.2-4.2.5.jar) 
	UCH	malisisdoors{1.10.2-5.1.3} [MalisisDoors] (malisisdoors-1.10.2-5.1.3.jar) 
	UCH	modernmetals{0.11.0} [Modern Metals] (ModernMetals-0.11.0.jar) 
	UCH	examplemod{1.0} [Example Mod] (Modifiable-Armor-2-1.10.2-2.0.2.jar) 
	UCH	modifiable_armor{2.0.2} [Modifiable Armor 2] (Modifiable-Armor-2-1.10.2-2.0.2.jar) 
	UCH	orespawn{1.1.0} [Ore Spawn] (OreSpawn_1.10.2-1.1.0.jar) 
	UCH	harvestcraft{1.9.4-1.10.2f} [Pam's HarvestCraft] (Pam's HarvestCraft 1.9.4-1.10.2f.jar) 
	UCH	redstonepaste{1.7.4} [Redstone Paste] (redstonepaste-mc1.9.4-1.7.4.jar) 
	UCH	storagenetwork{1.12.9} [Storage Network] (StorageNetwork-1.9.4-1.12.9.jar) 
	UCE	taiga{${version}} [Tinkers Alloying Addon] (taiga-1.10.2-1.1.2.jar) 
	UCH	Waila{1.7.0} [Waila] (Waila-1.7.0-B3_1.9.4.jar) 
	UCH	mcmultipart{1.2.0_74} [MCMultiPart] (MCMultiPart-experimental-1.2.0_74-universal.jar) 
	Loaded coremods (and transformers): 
MalisisCorePlugin (malisiscore-1.10.2-4.2.5.jar)
  net.malisis.core.util.chunkcollision.ChunkCollisionTransformer
  net.malisis.core.util.chunkblock.ChunkBlockTransformer
  net.malisis.core.renderer.transformer.MalisisRendererTransformer
  net.malisis.core.renderer.icon.asm.TextureMapTransformer
  net.malisis.core.util.clientnotif.ClientNotifTransformer
NWRTweak (redstonepaste-mc1.9.4-1.7.4.jar)
  net.fybertech.nwr.NWRTransformer
FMLPlugin (InventoryTweaks-1.61-58.jar)
  invtweaks.forge.asm.ContainerTransformer
LoadingPluginBuildingBricks (BuildingBricks-1.10.2-2.0.12.jar)
  com.hea3ven.buildingbricks.core.load.ClassTransformerBuildingBricks
	GL info: ' Vendor: 'Intel' Version: '4.3.0 - Build 20.19.15.4331' Renderer: 'Intel(R) HD Graphics 4400'
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- WailaIntegration (Enabled/Not Forced)

**Comment by IdleGandalf** [comment]
You have to use latest TAIGA 1.1.3 if you got TCon version 2.5, I'm closing this now.
