### ISSUE TITLE
Crash with Analysing trait

### ISSUE THREAD

**Issue by Codelax** [Zkaface/TAIGA#89]
Crash upon killing a VillagerGolem
```
[23:24:48] [Client thread/INFO]: [net.minecraft.init.Bootstrap:func_179870_a:560]: ---- Minecraft Crash Report ----

WARNING: coremods are present:
  CCLCorePlugin (CodeChickenLib.jar)
  ChiselCorePlugin (Chisel.jar)
  FMLPlugin (InventoryTweaks.jar)
  llibrary (Llibrary.jar)
  ForgelinPlugin (Forgelin.jar)
  LoadingPlugin (RandomThings.jar)
  BookshelfLoadingPlugin (Bookshelf-1.10.2-1.4.3.338.jar)
  literalascension (LiteralAscension.jar)
  AppleCore (AppleCore.jar)
  LoadingPlugin (Quark.jar)
Contact their authors BEFORE contacting forge

// Don't do that.

Time: 12/29/16 11:24 PM
Description: Ticking entity

java.lang.IllegalArgumentException: bound must be positive
	at java.util.Random.nextInt(Unknown Source)
	at com.sosnitzka.taiga.traits.TraitAnalysing.getUpdateXP(TraitAnalysing.java:55)
	at com.sosnitzka.taiga.traits.TraitAnalysing.onXpDrop(TraitAnalysing.java:29)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_317_TraitAnalysing_onXpDrop_LivingExperienceDropEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
	at net.minecraftforge.event.ForgeEventFactory.getExperienceDrop(ForgeEventFactory.java:217)
	at net.minecraft.entity.EntityLivingBase.func_70609_aI(EntityLivingBase.java:376)
	at net.minecraft.entity.EntityLivingBase.func_70030_z(EntityLivingBase.java:314)
	at net.minecraft.entity.EntityLiving.func_70030_z(EntityLiving.java:279)
	at net.minecraft.entity.Entity.func_70071_h_(Entity.java:359)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1932)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:384)
	at net.minecraft.world.World.func_72866_a(World.java:1964)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:839)
	at net.minecraft.world.World.func_72870_g(World.java:1934)
	at net.minecraft.world.World.func_72939_s(World.java:1750)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:620)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:240)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Unknown Source)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at java.util.Random.nextInt(Unknown Source)
	at com.sosnitzka.taiga.traits.TraitAnalysing.getUpdateXP(TraitAnalysing.java:55)
	at com.sosnitzka.taiga.traits.TraitAnalysing.onXpDrop(TraitAnalysing.java:29)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_317_TraitAnalysing_onXpDrop_LivingExperienceDropEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
	at net.minecraftforge.event.ForgeEventFactory.getExperienceDrop(ForgeEventFactory.java:217)
	at net.minecraft.entity.EntityLivingBase.func_70609_aI(EntityLivingBase.java:376)
	at net.minecraft.entity.EntityLivingBase.func_70030_z(EntityLivingBase.java:314)
	at net.minecraft.entity.EntityLiving.func_70030_z(EntityLiving.java:279)
	at net.minecraft.entity.Entity.func_70071_h_(Entity.java:359)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1932)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:384)
	at net.minecraft.world.World.func_72866_a(World.java:1964)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:839)
	at net.minecraft.world.World.func_72870_g(World.java:1934)

-- Entity being ticked --
Details:
	Entity Type: VillagerGolem (net.minecraft.entity.monster.EntityIronGolem)
	Entity ID: 5230
	Entity Name: Iron Golem
	Entity's Exact location: -136.10, 63.00, 163.44
	Entity's Block location: World: (-137,63,163), Chunk: (at 7,3,3 in -9,10; contains blocks -144,0,160 to -129,255,175), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1750)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:620)

-- Affected level --
Details:
	Level name: testlol
	All players: 1 total; [EntityPlayerMP['<PROFILE NAME>'/1018, l='testlol', x=-133.19, y=63.00, z=164.27]]
	Chunk stats: ServerChunkCache: 490 Drop: 0
	Level seed: -6503423906325025648
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: {"diamondSize":8,"lapisCenterHeight":16,"lavaLakeChance":80,"redstoneMaxHeight":16,"diamondMaxHeight":16,"coalMaxHeight":128,"coalMinHeight":0,"seaLevel":63,"graniteCount":10,"riverSize":4,"gravelMinHeight":0,"graniteSize":33,"redstoneSize":8,"fixedBiome":-1,"waterLakeChance":4,"dioriteMinHeight":0,"andesiteCount":10,"graniteMaxHeight":80,"redstoneMinHeight":0,"lapisSize":7,"dirtCount":10,"ironMinHeight":0,"dioriteMaxHeight":80,"coalCount":20,"gravelCount":8,"coalSize":17,"gravelSize":33,"ironMaxHeight":64,"lapisSpread":16,"dioriteCount":10,"andesiteSize":33,"biomeSize":4,"graniteMinHeight":0,"goldCount":2,"diamondCount":1,"dirtSize":33,"gravelMaxHeight":256,"goldSize":9,"ironCount":20,"diamondMinHeight":0,"ironSize":9,"redstoneCount":8,"andesiteMinHeight":0,"dioriteSize":33,"goldMaxHeight":32,"dungeonChance":8,"andesiteMaxHeight":80,"dirtMinHeight":0,"lapisCount":1,"goldMinHeight":0,"dirtMaxHeight":256,"lowerLimitScale":512.0,"biomeDepthOffset":0.0,"upperLimitScale":512.0,"heightScale":684.412,"biomeScaleWeight":1.0,"biomeDepthWeight":1.0,"mainNoiseScaleZ":80.0,"mainNoiseScaleY":160.0,"depthNoiseScaleX":200.0,"mainNoiseScaleX":80.0,"baseSize":8.5,"depthNoiseScaleZ":200.0,"stretchY":12.0,"depthNoiseScaleExponent":0.5,"biomeScaleOffset":0.0,"coordinateScale":684.412,"useStrongholds":true,"useMineShafts":true,"useTemples":true,"useLavaOceans":false,"useCaves":true,"useWaterLakes":true,"useLavaLakes":true,"useMonuments":true,"useRavines":true,"useDungeons":true,"useVillages":true}
	Level spawn location: World: (-158,64,238), Chunk: (at 2,4,14 in -10,14; contains blocks -160,0,224 to -145,255,239), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 1350 game time, 1350 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 140335 (now: false), thunder time: 61885 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:240)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Unknown Source)

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_111, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2537718696 bytes (2420 MB) / 4728029184 bytes (4509 MB) up to 7494172672 bytes (7147 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx8040m
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP 9.32 Powered by Forge 12.18.3.2185 Optifine OptiFine_1.10.2_HD_U_D4 61 mods loaded, 61 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.3.2185-universal.jar) 
	UCHIJAAAA	Forge{12.18.3.2185} [Minecraft Forge] (forge-1.10.2-12.18.3.2185-universal.jar) 
	UCHIJAAAA	ccl-entityhook{1.0} [ccl-entityhook] (CodeChickenLib.jar) 
	UCHIJAAAA	JEI{3.13.6.387} [Just Enough Items] (JEI.jar) 
	UCHIJAAAA	AppleCore{2.1.0} [AppleCore] (AppleCore.jar) 
	UCHIJAAAA	appleskin{1.0.4} [AppleSkin] (AppleSkin.jar) 
	UCHIJAAAA	mantle{1.10.2-1.1.3.199} [Mantle] (Mantle.jar) 
	UCHIJAAAA	tconstruct{1.10.2-2.6.1.464} [Tinkers' Construct] (TConstruct.jar) 
	UCHIJAAAA	thedragonlib{1.10.2-1.0.3.0} [TheDragonLib] (thedragonlib.jar) 
	UCHIJAAAA	armorplus{1.10.2-8.2.3.4} [ArmorPlus] (armorplus.jar) 
	UCHIJAAAA	Quark{r1.1-66} [Quark] (Quark.jar) 
	UCHIJAAAA	AutoRegLib{1.0-2} [AutoRegLib] (AutoRegLib.jar) 
	UCHIJAAAA	betterquesting{2.3.191} [Better Questing] (BetterQuesting.jar) 
	UCHIJAAAA	bq_standard{2.3.118} [Standard Expansion] (BetterQuesting_StandardExpansion.jar) 
	UCHIJAAAA	BetterSprinting{1.1.7} [Better Sprinting] (BetterSprinting.jar) 
	UCHIJAAAA	bookshelf{1.4.3.338} [Bookshelf] (Bookshelf-1.10.2-1.4.3.338.jar) 
	UCHIJAAAA	Chameleon{1.10-2.2.2} [Chameleon] (ChameleonLibrary.jar) 
	UCHIJAAAA	ChestTransporter{2.5.6} [Chest Transporter] (ChestTransporter.jar) 
	UCHIJAAAA	chisel{MC1.10.2-0.0.7.7} [Chisel] (Chisel.jar) 
	UCHIJAAAA	CodeChickenLib{2.5.0.178} [CodeChicken Lib] (CodeChickenLib.jar) 
	UCHIJAAAA	CodeChickenCore{2.4.0.100} [CodeChicken Core] (CodeChickenCore.jar) 
	UCHIJAAAA	cookingforblockheads{4.2.26} [Cooking for Blockheads] (CookingForBlockheads.jar) 
	UCHIJAAAA	MineTweaker3{3.0.14} [MineTweaker 3] (CraftTweaker.jar) 
	UCHIJAAAA	ctgui{1.0.0} [CT-GUI] (CraftTweaker.jar) 
	UCHIJAAAA	CustomMainMenu{2.0.2} [Custom Main Menu] (CustomMainMenu.jar) 
	UCHIJAAAA	eplus{4.1.0.113} [Enchanting Plus] (EnchantingPlus-1.10.2-4.1.0.115.jar) 
	UCHIJAAAA	endercompass{1.2.3.2} [Ender Compass] (EnderCompass.jar) 
	UCHIJAAAA	EnderStorage{2.2.0.96} [EnderStorage] (EnderStorage.jar) 
	UCHIJAAAA	FastLeaveDecay{1.2.3} [Fast Leave Decay] (FastLeaveDecay.jar) 
	UCHIJAAAA	Waila{1.7.0} [Waila] (Waila.jar) 
	UCHIJAAAA	ftbl{0.0.0} [FTBLib] (FTBLib.jar) 
	UCHIJAAAA	ftbu{0.0.0} [FTBUtilities] (FTBUtilities.jar) 
	UCHIJAAAA	hardcorewither{2.2.3} [Hardcore Wither] (HardcoreWither.jar) 
	UCHIJAAAA	InventoryPets{1.4.9} [Inventory Pets] (InventoryPets.jar) 
	UCHIJAAAA	inventorytweaks{1.61-58-a1fd884} [Inventory Tweaks] (InventoryTweaks.jar) 
	UCHIJAAAA	ironbackpacks{1.10.2-2.2.21} [Iron Backpacks] (IronBackpacks.jar) 
	UCHIJAAAA	ironchest{1.10.2-7.0.11.797} [Iron Chest] (IronChest.jar) 
	UCHIJAAAA	journeymap{1.10.2-5.3.2} [JourneyMap] (JourneyMap.jar) 
	UCHIJAAAA	jeresources{0.5.8.98} [Just Enough Resources] (JustEnoughResources.jar) 
	UCHIJAAAA	llibrary{1.7.2} [LLibrary] (Llibrary.jar) 
	UCHIJAAAA	literalascension{1.10.2-1.0.0.1} [Literal Ascension] (LiteralAscension.jar) 
	UCHIJAAAA	minemenu{1.4.4} [MineMenu] (MineMenu.jar) 
	UCHIJAAAA	testdummy{1.11} [MmmMmmMmmMmm] (MmmMmmMmmMmm.jar) 
	UCHIJAAAA	Morpheus{1.10.2-3.1.12} [Morpheus] (Morpheus.jar) 
	UCHIJAAAA	naturescompass{1.3.0} [Nature's Compass] (NaturesCompass.jar) 
	UCHIJAAAA	netherportalfix{1.0} [Nether Portal Fix] (NetherPortalFix.jar) 
	UCHIJAAAA	harvestcraft{1.9.4-1.10.2g} [Pam's HarvestCraft] (Pam's_HarvestCraft.jar) 
	UCHIJAAAA	ping{1.2.2} [Ping] (Ping.jar) 
	UCHIJAAAA	randomthings{3.7.7} [Random Things] (RandomThings.jar) 
	UCHIJAAAA	RTG{4.1.2.1} [Realistic Terrain Generation] (RTG.jar) 
	UCHIJAAAA	shadowmc{3.5.0} [ShadowMC] (ShadowMC.jar) 
	UCHIJAAAA	SleepingBag{1.4.0} [Sleeping Bag] (SleepingBag.jar) 
	UCHIJAAAA	StorageDrawers{1.10.2-3.5.14} [Storage Drawers] (StorageDrawers.jar) 
	UCHIJAAAA	supercraftingframe{1.2.1.88} [Super Crafting Frame] (SuperCraftingFrame.jar) 
	UCHIJAAAA	taiga{1.2.2} [Tinkers Alloying Addon] (taiga-1.10.2-1.2.2.jar) 
	UCHIJAAAA	tinkertoolleveling{1.10.2-1.0.1.DEV.f5def58} [Tinkers Tool Leveling] (TinkerToolLeveling.jar) 
	UCHIJAAAA	torohealthmod{1.10.2-7} [ToroHealth Damage Indicators] (ToroHealth.jar) 
	UCHIJAAAA	WailaHarvestability{1.1.9} [Waila Harvestability] (WailaHarvestability.jar) 
	UCHIJAAAA	icse{1.1.0.0} [I Can See Everything] (Wawla.jar) 
	UCHIJAAAA	wawla{2.3.1.213} [What Are We Looking At] (Wawla.jar) 
	Loaded coremods (and transformers): 
CCLCorePlugin (CodeChickenLib.jar)
  codechicken.lib.asm.ClassHeirachyManager
  codechicken.lib.asm.BlockStateLoaderTransformer
ChiselCorePlugin (Chisel.jar)
  team.chisel.common.asm.ChiselTransformer
FMLPlugin (InventoryTweaks.jar)
  invtweaks.forge.asm.ContainerTransformer
llibrary (Llibrary.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
ForgelinPlugin (Forgelin.jar)
  
LoadingPlugin (RandomThings.jar)
  lumien.randomthings.asm.ClassTransformer
BookshelfLoadingPlugin (Bookshelf-1.10.2-1.4.3.338.jar)
  net.darkhax.bookshelf.asm.BookshelfTransformerManager
literalascension (LiteralAscension.jar)
  com.jamieswhiteshirt.literalascension.core.patcher.LiteralAscensionRuntimePatcher
AppleCore (AppleCore.jar)
  squeek.applecore.asm.TransformerModuleHandler
LoadingPlugin (Quark.jar)
  vazkii.quark.base.asm.ClassTransformer
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- WailaIntegration (Enabled/Not Forced)

	CodeChickenLib Invalid Fingerprint Reports: 
	CodeChickenCore Invalid Fingerprint Reports: 
	EnderStorage Invalid Fingerprint Reports: 
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['<PROFILE NAME>'/1018, l='testlol', x=-133.19, y=63.00, z=164.27]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	OptiFine Version: OptiFine_1.10.2_HD_U_D4
	Render Distance Chunks: 10
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.5.0 NVIDIA 376.19
	OpenGlRenderer: GeForce GTX 1060 6GB/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 4
	The 5zig Mod Version: 3.9.19
	The 5zig Mod Plugins: []
	Forge: true
	GUI: ~~NULL~~
```

**Comment by IdleGandalf** [comment]
Fix will be in the next release.
